#!/bin/bash
## Usage: devserver COMMAND
##
## Command can be:
## - init           create a new devserver from a stock image
## - start          create a new devserver from a previous snapshot
## - stop           snapshot the existing devserver and destroy it

set -e

usage() {
  sed -ne "/^##/{s/^## *//"$'\n'"p"$'\n'"}" $0
}

if [ "$#" -eq 0 ]; then
  usage >&2
  exit 1
fi

cd "$(dirname "$(python -c "import os; print(os.path.realpath('$0'))")")"
if [ ! -f .env ]; then
  echo "Copy .env.example to .env and edit before running."
fi

CMD=$1
shift
if [ "$CMD" = "start" ]; then
  ./start.sh "$@"
elif [ "$CMD" = "stop" ]; then
  ./stop.sh "$@"
elif [ "$CMD" = "init" ]; then
  ./init.sh "$@"
elif [ "$CMD" = "--help" ]; then
  usage >&2
else
  usage >&2
  exit 1
fi
