#!/bin/bash
## Usage: devserver COMMAND
##
## Command can be:
## - init           set up your first devserver
## - start          start the devserver
## - stop           stop the devserver

set -e

usage() {
  sed -ne "/^##/{s/^## *//"$'\n'"p"$'\n'"}" $0
}

if [ "$#" -eq 0 ]; then
  usage >&2
  exit 1
fi

cd "$(dirname "$(python -c "import os; print(os.path.realpath('$0'))")")"
. .envrc

CMD=$1
shift
if [ "$CMD" = "init" ]; then
  ./init.sh "$@"
elif [ "$CMD" = "start" ]; then
  ./start.sh "$@"
elif [ "$CMD" = "stop" ]; then
  ./stop.sh "$@"
elif [ "$CMD" = "--help" ]; then
  usage >&2
else
  usage >&2
  exit 1
fi
